# Generated by Django 5.2.8 on 2025-11-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="images", verbose_name="Изображение"),
        ),
    ]
